# Generated by Django 3.2.5 on 2021-08-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='World', max_length=300),
        ),
    ]
